SwShDict = {
    "Sword & Shield Promo" : "swshp",
    "Sword & Shield" : "swsh1",
    "Rebel Clash" : "swsh2",
    "Darkness Ablaze" : "swsh3",
    "Champion’s Path" : "swsh35",
    "Vivid Voltage" : "swsh4",
    "Shining Fates" : "swsh45",
    "Shining Fates: Shiny Vault" : "swsh45sv",
    "Battle Styles" : "swsh5",
    "Chilling Reign" : "swsh6",
    "Evolving Skies" : "swsh7",
    "Celebrations" : "cel25",
    "Celebrations: Classic Collection" : "cel25c",
    "Fusion Strike" : "swsh8",
    "Brilliant Stars" : "swsh9",
    "Brilliant Stars Trainer Gallery" : "swsh9tg",
    "Astral Radiance" : "swsh10",
    "Astral Radiance Trainer Gallery" : "swsh10",
    "Pokémon TCG: Pokémon GO" : "pgo",
    "Lost Origin" : "swsh11",
    "Lost Origin Trainer Gallery" : "swsh11tg",
    "Silver Tempest" : "swsh12",
    "Silver Tempest: Trainer Gallery" : "swsh12tg",
    "Crown Zenith" : "swsh12pt5",
    "Crown Zenith Galarian Gallery" : "swsh12pt5gg" 
}